# Save this file code as write_local_data.py inside your project directory
with open("India_City_Land_Costs_Only.csv", "w", encoding="utf-8") as f:
    f.write("City,State,Avg Land Price (rupees_per_sqft)\n")
    f.write("Mumbai,Maharashtra,25000\n")
    f.write("New Delhi,Delhi NCR,22000\n")
    f.write("Dwarka,Delhi NCR,15000\n")
    f.write("Chandigarh,Chandigarh UT,14500\n")
    f.write("Bengaluru,Karnataka,13000\n")
    f.write("Gurugram,Haryana,12500\n")
    f.write("Hyderabad,Telangana,9800\n")
    f.write("Noida,Uttar Pradesh,8500\n")
    f.write("Chennai,Tamil Nadu,7800\n")
    f.write("Panaji,Goa,7500\n")
    f.write("Faridabad,Haryana,7500\n")
    f.write("Ludhiana,Punjab,6300\n")
    f.write("Mohali,Punjab,6000\n")
    f.write("Kochi,Kerala,5900\n")
    f.write("Visakhapatnam,Andhra Pradesh,5600\n")
    f.write("Ahmedabad,Gujarat,5600\n")
    f.write("Lucknow,Uttar Pradesh,5400\n")
    f.write("Kolkata,West Bengal,5200\n")
    f.write("Thiruvananthapuram,Kerala,5200\n")
    f.write("Jaipur,Rajasthan,4900\n")
    f.write("Mysuru,Karnataka,4800\n")
    f.write("Dehradun,Uttarakhand,4300\n")
    f.write("Indore,Madhya Pradesh,4200\n")
    f.write("Bhopal,Madhya Pradesh,4200\n")
    f.write("Coimbatore,Tamil Nadu,4200\n")
    f.write("Patna,Bihar,4100\n")
    f.write("Surat,Gujarat,4100\n")
    f.write("Vadodara,Gujarat,3900\n")
    f.write("Bhubaneswar,Odisha,3900\n")
    f.write("Agra,Uttar Pradesh,3800\n")
    f.write("Varanasi,Uttar Pradesh,3800\n")
    f.write("Jammu,Jammu & Kashmir,3500\n")
    f.write("Srinagar,Jammu & Kashmir,3500\n")
    f.write("Ranchi,Jharkhand,3400\n")
    f.write("Jamshedpur,Jharkhand,3400\n")
    f.write("Warangal,Telangana,3200\n")
    f.write("Shimla,Himachal Pradesh,3200\n")
    f.write("Raipur,Chhattisgarh,3100\n")
    f.write("Bhilai,Chhattisgarh,3100\n")
    f.write("Guwahati,Assam,2900\n")
    f.write("Siliguri,West Bengal,2800\n")
    f.write("Puducherry,Puducherry UT,2700\n")
    f.write("Nashik,Maharashtra,2500\n")
    f.write("Nagpur,Maharashtra,2500\n")
    f.write("Shillong,Meghalaya,2200\n")
    f.write("Agartala,Tripura,1800\n")
    f.write("Leh,Ladakh UT,1700\n")
    f.write("Imphal,Manipur,1600\n")
    f.write("Itanagar,Arunachal Pradesh,1500\n")
    f.write("Kohima,Nagaland,1500\n")
    f.write("Aizawl,Mizoram,1400\n")

print("Success! File locally initialized as 'India_City_Land_Costs_Only.csv'")
