export type DataStatus = "observed" | "derived" | "proxy" | "assumption" | "unavailable";

export type OpportunityFactor = {
  key: string;
  label: string;
  value: number | null;
  weight: number | null;
  contribution: number | null;
  status: DataStatus;
  explanation: string;
  sourceLabel?: string;
};

export type Opportunity = {
  id: string;
  name: string;
  state: string;
  districtOrCity: string;
  parentId?: string;
  level: "state" | "district" | "zone" | "candidate-site";
  latitude: number;
  longitude: number;
  opportunityScore: number;
  opportunityBand: "high" | "medium" | "low";
  evDemandIndex: number;
  evGrowthIndex: number;
  chargingGapIndex: number;
  existingChargerCountEstimate: number;
  competitionIndex: number;
  roadAccessIndex: number;
  solarPotentialIndex: number;
  electricityCostIndex: number | null;
  targetSegments: string[];
  chargerTypes: string[];
  estimatedBudgetBand: string;
  factors: OpportunityFactor[];
  whyHereSummary: string;
  risks: string[];
  dataStatus: "observed-and-derived" | "illustrative-demo";
  totalRegistrations: number;
  growthRatePct?: number;
  stationCount: number;
  fastChargers?: number;
  evPerCharger: number;
  solarUnitsPerKwMonth: number;
  annualSolarGenKwhPerKw: number;
  landPriceSqft: number;
  landMatchType: string;
  geoSource: string;
  history?: Array<{ month: string; count: number }>;
};

export type StationConfiguration = {
  name: string;
  description: string;
  chargerSetup: string;
  chargerCount: number;
  chargerType: "AC" | "DC" | "Mixed";
  hardwareCapex: number;
  gridCapex: number;
  solarKw: number;
  solarCapex: number;
  landSqft: number;
  landPurchaseCapex: number;
  totalCapex: number;
  monthlyLeaseRate: number;
  dailySessions: number;
  annualEnergySoldKwh: number;
  annualGrossRevenue: number;
  annualGridEnergyCost: number;
  annualSolarUnitsGen: number;
  annualSolarSavings: number;
  annualOperatingCost: number;
  annualNetCashFlow: number;
  simplePaybackYears: number | null;
  fiveYearRoiPct: number;
};

export type FinancialAssumptions = {
  chargerCount: number;
  chargerType: "AC" | "DC" | "Mixed";
  utilizationRate: number;
  avgKwhPerSession: number;
  sellingPricePerKwh: number;
  electricityCostPerKwh: number;
  installationCost: number;
  monthlyRent: number;
  monthlyMaintenance: number;
  solarCapacityKw: number;
  solarCostPerKw: number;
};
